name: react-package-ci

on:
  # pull_request:
  #   branches: ["al-react-components/al-spinner"]
  #   paths:
  #     - "**/web/**"
  #     - "**/react-package-ci.yml"
  push: # TODO: Remove when done testing #
    paths:
      - "al-react-components/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: "al-react-components/yarn.lock"

      - name: Install and build
        run: |
          cd al-react-components
          yarn
          yarn workspaces run build